import os
import codecs
import json


def new_stock():
    stock={}
    stock['0']='1:sh,51:sz'
    stock['1'] = '名称'
    stock['2'] = '代码'
    stock['3']='当前价'
    stock['4']='昨收'
    stock['5']='今开'
    stock['6'] = '成交量（手）'
    stock['7'] = '外盘'
    stock['8'] = '内盘'
    stock['9'] = '买1金额'
    stock['10'] = '买1数量'
    stock['11'] = '买2金额'
    stock['12'] = '买2数量'
    stock['13'] = '买3金额'
    stock['14'] = '买3数量'
    stock['15']='买4金额'
    stock['16']='买4数量'
    stock['17']='买5金额'
    stock['18']='买5数量'
    stock['19']='卖1金额'
    stock['20']='卖1数额'
    stock['21']='卖2金额'
    stock['22']='卖2数额'
    stock['23']='卖3金额'
    stock['24']='卖3数额'
    stock['25']='卖4金额'
    stock['26']='卖4数额'
    stock['27']='卖5金额'
    stock['28']='卖5数额'
    stock['29']='时间	成交价(元)	成交量	性质  金额'
    stock['30']='时间'
    stock['31']='涨幅'
    stock['32']='涨幅比'
    stock['33']='最高'
    stock['34']='最低'
    stock['35']='现价/成交量/成交额'
    stock['36']='成交量'
    stock['37']='成交额（万）'
    stock['38']='换手率'
    stock['39']='市盈率'
    stock['40']=''
    stock['41']='最高'
    stock['42']='最低'
    stock['43']='振幅'
    stock['44']='流通市值'
    stock['45']='总市值'
    stock['46']='市净率'
    stock['47']='分时坐标最高'
    stock['48']='分时标最低'
    stock['49']=''
    stock['50']='委差'
    stock['51']=''
    stock['52']=''
    stock['53']=''
    stock['54']=''
    stock['55']=''
    stock['56']=''
    stock['57']='成交额'
    return stock
